package com.planbook.service.teacher;

import static org.mockito.Mockito.when;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;


import com.planbook.dto.PromptDTO;
import com.planbook.dto.teacher.LessonPlanRequest;
import com.planbook.dto.teacher.LessonPlanResponse; 
import com.planbook.entity.admin.CurriculumTemplate;
import com.planbook.repository.admin.CurriculumTemplateRepository;
import com.planbook.service.AiPromptService;


@SpringBootTest
public class LessonPlanServiceTest {

    @Autowired
    private LessonPlanService lessonPlanService;

    @Autowired
    private CurriculumTemplateRepository curriculumTemplateRepository;

    @MockBean
    private AiPromptService aiPromptService;

    private Long templateId; // lưu id thực tế sau khi save

    @BeforeEach
    void setup() {
        // Tạo curriculum template mới và lưu vào DB
        CurriculumTemplate template = new CurriculumTemplate();
        template.setName("Test Template");
        template.setDescription("Template for testing");
        CurriculumTemplate saved = curriculumTemplateRepository.save(template);

        // Lấy id thực tế vừa được sinh
        templateId = saved.getId();

        // 👇 MOCK AI RESPONSE
        PromptDTO.PromptResponse mockPrompt = new PromptDTO.PromptResponse();
        mockPrompt.setContent("Generated by AI");
        mockPrompt.setName("AI Title");

        when(aiPromptService.getActivePrompt("lessonplan_template"))
            .thenReturn(mockPrompt);
    }

    @Test
    void testAddLessonPlanWithEmptyContent() {
        LessonPlanRequest request = new LessonPlanRequest();
        request.setTitle("");
        request.setContent("");
        request.setTopicId(1L);                 // giả sử có topic id=1
        request.setCurriculumTemplateId(templateId); // dùng id vừa seed

        LessonPlanResponse response = lessonPlanService.addLessonPlan(request, 1L);

        assertNotNull(response);
        assertNotNull(response.getContent(), "Content phải được sinh từ AI khi rỗng");
        System.out.println(">>> AI generated content: " + response.getContent());
    }
}
